# Generated by Cascade on 2025-11-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_seed_taxonomy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("responses", models.JSONField(help_text="Raw responses keyed by question identifier.")),
                ("highlights", models.JSONField(blank=True, default=list, help_text="Highlights derived from scoring.")),
                ("score", models.JSONField(blank=True, default=dict, help_text="Calculated scoring payload including totals and bands.")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("assessment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="assessments.assessment")),
                ("client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assessment_responses", to="clients.client")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assessment_responses_submitted", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.AddIndex(
            model_name="assessmentresponse",
            index=models.Index(fields=["assessment", "submitted_at"], name="assessresp_assess_submitted_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentresponse",
            index=models.Index(fields=["client", "submitted_at"], name="assessresp_client_submitted_idx"),
        ),
    ]
