# Generated by Django 5.2.7 on 2025-11-08 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentresponse'),
        ('clients', '0002_clientgroup_clientgroupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentInviteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessments', models.JSONField(help_text='Assessment slugs included in this schedule')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('include_consent', models.BooleanField(default=True)),
                ('share_results', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField()),
                ('frequency', models.CharField(max_length=32)),
                ('cycles', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespondentInviteScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('scheduled_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='assessmentresponse',
            new_name='assessments_assessm_fa4b79_idx',
            old_name='assessresp_assess_submitted_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentresponse',
            new_name='assessments_client__adfdd6_idx',
            old_name='assessresp_client_submitted_idx',
        ),
        migrations.AddField(
            model_name='respondentinviteschedule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_invite_schedules', to='clients.client'),
        ),
        migrations.AddField(
            model_name='respondentinviteschedule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_invite_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respondentinviteschedulerun',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='assessments.respondentinviteschedule'),
        ),
    ]
