# Generated by Cascade assistant

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_respondentinviteschedule_respondentinviteschedulerun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="respondentinviteschedule",
            name="reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
