# Generated by Django 5.2.7 on 2025-11-08 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_respondentinviteschedule_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentinviteschedule',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
