# Generated by Django 5.2.7 on 2025-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_respondentinviteschedule_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='domain',
            field=models.CharField(default='general', help_text='Cognitive or skill domain this question targets.', max_length=120),
        ),
    ]
