# Generated by Django 5.2.7 on 2025-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessmentquestion_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='clinician_notes',
            field=models.TextField(blank=True),
        ),
    ]
