# Generated by Cascade on 2025-11-22
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_clientgroup_clientgroupmembership"),
        ("assessments", "0008_assessment_clinician_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RespondentInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255, unique=True)),
                ("assessments", models.JSONField(help_text="Assessment slugs embedded in this invitation")),
                ("mode", models.CharField(max_length=20)),
                ("share_results", models.BooleanField(default=False)),
                ("pending_client", models.BooleanField(default=False)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("max_uses", models.PositiveSmallIntegerField(default=1)),
                ("uses", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="respondent_invites", to="clients.client")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="respondent_invites", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="assessments_respon_token_idx"),
                    models.Index(fields=["owner", "issued_at"], name="assessments_respon_owner_issued_idx"),
                    models.Index(fields=["expires_at"], name="assessments_respon_expires_idx"),
                ],
            },
        ),
    ]