# Generated by Django 5.2.7 on 2025-11-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_respondentinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='respondentinvite',
            new_name='assessments_token_1714f4_idx',
            old_name='assessments_respon_token_idx',
        ),
        migrations.RenameIndex(
            model_name='respondentinvite',
            new_name='assessments_owner_i_7adc73_idx',
            old_name='assessments_respon_owner_issued_idx',
        ),
        migrations.RenameIndex(
            model_name='respondentinvite',
            new_name='assessments_expires_07bafa_idx',
            old_name='assessments_respon_expires_idx',
        ),
    ]
