# Generated by Django 5.2.7 on 2025-12-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_rename_assessments_respon_token_idx_assessments_token_1714f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentinvite',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
