# Generated by Django 5.2.7 on 2025-12-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_alter_respondentinvite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentinviteschedulerun',
            name='token',
            field=models.TextField(),
        ),
    ]
