# Generated by Django 5.2.7 on 2025-11-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('diverse', 'Gender diverse or non-binary')], max_length=16)),
                ('groups', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_assessed', models.DateField(blank=True, null=True)),
                ('informant1_name', models.CharField(blank=True, max_length=150)),
                ('informant1_email', models.EmailField(blank=True, max_length=254)),
                ('informant2_name', models.CharField(blank=True, max_length=150)),
                ('informant2_email', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(max_length=180)),
                ('owner', models.ForeignKey(help_text='Clinician who manages this client record.', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('owner', 'slug')},
            },
        ),
    ]
