# Generated by Django 5.2.7 on 2025-11-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_practitioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='redirect_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reply_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='reply_mode',
            field=models.CharField(choices=[('none', 'Do not allow replies'), ('practitioner', 'Reply to practitioner'), ('custom', 'Reply to custom address')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('dr', 'Dr'), ('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('prof', 'Prof')], max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
