# Generated by Django 5.2.7 on 2025-11-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_user_id_8cd138_idx',
            old_name='accounts_pa_user_id_f22042_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_expires_01b447_idx',
            old_name='accounts_pa_expires_1ccf75_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_h_2771ed_idx',
            old_name='accounts_pa_token_ha_3ab43f_idx',
        ),
        migrations.RenameIndex(
            model_name='twofactorchallenge',
            new_name='accounts_tw_user_id_066672_idx',
            old_name='accounts_tw_user_chal_5b124b_idx',
        ),
        migrations.RenameIndex(
            model_name='twofactorchallenge',
            new_name='accounts_tw_expires_af259a_idx',
            old_name='accounts_tw_expires_ea2213_idx',
        ),
    ]
