# Generated by Django 5.2.7 on 2026-01-30 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_is_approved_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('code_hash', models.CharField(max_length=128)),
                ('code_salt', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'challenge_id'], name='accounts_si_email_6cfdf8_idx'), models.Index(fields=['expires_at'], name='accounts_si_expires_db4256_idx')],
            },
        ),
    ]
