# Generated by Django 5.2.7 on 2026-08-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, help_text="Snapshot of the acting user's email, so the trail survives account deletion.", max_length=254)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('EXPORT', 'Export'), ('SUBMIT', 'Submit')], max_length=16)),
                ('resource_type', models.CharField(choices=[('client', 'Client'), ('client_group', 'Client group'), ('assessment_response', 'Assessment response')], max_length=32)),
                ('resource_id', models.CharField(blank=True, help_text='Primary key of the affected record. Identifier only.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Acting user. Null for unauthenticated respondent actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx')],
            },
        ),
    ]
